'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Enrollment
    Public Property EnrollmentID As Integer
    Public Property Grade As Nullable(Of Decimal)
    Public Property CourseID As Integer
    Public Property StudentID As Integer

    Public Overridable Property Course As Course
    Public Overridable Property Student As Student

End Class
